# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Findmypast Front End Design Home
email: andy.briggs@findmypast.com
description: > # this means to ignore newlines until "baseurl:"
  Home of best practices and design standards for Findmypast
baseurl: "/fmp-design" # the subpath of your site, e.g. /blog
url: "http://andybriggs.github.io/fmp-design" # the base hostname & protocol for your site
twitter_username: ajnBriggs
github_username:  andybriggs

# Build settings
markdown: kramdown
